/**
 * This file is part of the hry-core project
 * @ Author: Piotr Krupa <piotrkrupa06@gmail.com>
 * @ License: MIT License
 */

#include "Hry/KeyBinding/BindableKeys.hpp"

#include <algorithm>

HRY_NS_BEGIN

static const auto BindableKeys = std::array{
    // Keyboard
    BindableKey{ Keyboard::Key::A, "A" },
    BindableKey{ Keyboard::Key::B, "B" },
    BindableKey{ Keyboard::Key::C, "C" },
    BindableKey{ Keyboard::Key::D, "D" },
    BindableKey{ Keyboard::Key::E, "E" },
    BindableKey{ Keyboard::Key::F, "F" },
    BindableKey{ Keyboard::Key::G, "G" },
    BindableKey{ Keyboard::Key::H, "H" },
    BindableKey{ Keyboard::Key::I, "I" },
    BindableKey{ Keyboard::Key::J, "J" },
    BindableKey{ Keyboard::Key::K, "K" },
    BindableKey{ Keyboard::Key::L, "L" },
    BindableKey{ Keyboard::Key::M, "M" },
    BindableKey{ Keyboard::Key::N, "N" },
    BindableKey{ Keyboard::Key::O, "O" },
    BindableKey{ Keyboard::Key::P, "P" },
    BindableKey{ Keyboard::Key::Q, "Q" },
    BindableKey{ Keyboard::Key::R, "R" },
    BindableKey{ Keyboard::Key::S, "S" },
    BindableKey{ Keyboard::Key::T, "T" },
    BindableKey{ Keyboard::Key::U, "U" },
    BindableKey{ Keyboard::Key::V, "V" },
    BindableKey{ Keyboard::Key::W, "W" },
    BindableKey{ Keyboard::Key::X, "X" },
    BindableKey{ Keyboard::Key::Y, "Y" },
    BindableKey{ Keyboard::Key::Z, "Z" },
    BindableKey{ Keyboard::Key::Num0, "0" },
    BindableKey{ Keyboard::Key::Num1, "1" },
    BindableKey{ Keyboard::Key::Num2, "2" },
    BindableKey{ Keyboard::Key::Num3, "3" },
    BindableKey{ Keyboard::Key::Num4, "4" },
    BindableKey{ Keyboard::Key::Num5, "5" },
    BindableKey{ Keyboard::Key::Num6, "6" },
    BindableKey{ Keyboard::Key::Num7, "7" },
    BindableKey{ Keyboard::Key::Num8, "8" },
    BindableKey{ Keyboard::Key::Num9, "9" },
    // BindableKey{ Keyboard::Key::Escape, "Escape" }, # DISABLED
    BindableKey{ Keyboard::Key::LControl, "Left Ctrl" },
    BindableKey{ Keyboard::Key::LShift, "Left Shift" },
    BindableKey{ Keyboard::Key::LAlt, "Left Alt" },
    BindableKey{ Keyboard::Key::LSystem, "Left System" },
    BindableKey{ Keyboard::Key::RControl, "Right Ctrl" },
    BindableKey{ Keyboard::Key::RShift, "Right Shift" },
    BindableKey{ Keyboard::Key::RAlt, "Right Alt" },
    BindableKey{ Keyboard::Key::RSystem, "Right System" },
    BindableKey{ Keyboard::Key::Menu, "Menu" },
    BindableKey{ Keyboard::Key::LBracket, "{" },
    BindableKey{ Keyboard::Key::RBracket, "}" },
    BindableKey{ Keyboard::Key::Semicolon, ";" },
    BindableKey{ Keyboard::Key::Comma, "," },
    BindableKey{ Keyboard::Key::Period, "." },
    BindableKey{ Keyboard::Key::Quote, "\"" },
    BindableKey{ Keyboard::Key::Slash, "/" },
    BindableKey{ Keyboard::Key::Backslash, "\\" },
    BindableKey{ Keyboard::Key::Tilde, "~" },
    BindableKey{ Keyboard::Key::Equal, "=" },
    BindableKey{ Keyboard::Key::Hyphen, "-" },
    BindableKey{ Keyboard::Key::Space, "Space" },
    BindableKey{ Keyboard::Key::Enter, "Enter" },
    BindableKey{ Keyboard::Key::Backspace, "Backspace" },
    BindableKey{ Keyboard::Key::Tab, "Tab" },
    BindableKey{ Keyboard::Key::PageUp, "PageUp" },
    BindableKey{ Keyboard::Key::PageDown, "PageDown" },
    BindableKey{ Keyboard::Key::End, "End" },
    BindableKey{ Keyboard::Key::Home, "Home" },
    BindableKey{ Keyboard::Key::Insert, "Insert" },
    BindableKey{ Keyboard::Key::Delete, "Delete" },
    BindableKey{ Keyboard::Key::Add, "Add" },
    BindableKey{ Keyboard::Key::Subtract, "Subtract" },
    BindableKey{ Keyboard::Key::Multiply, "Multiply" },
    BindableKey{ Keyboard::Key::Divide, "Divide" },
    BindableKey{ Keyboard::Key::Left, "Left" },
    BindableKey{ Keyboard::Key::Right, "Right" },
    BindableKey{ Keyboard::Key::Up, "Up" },
    BindableKey{ Keyboard::Key::Down, "Down" },
    BindableKey{ Keyboard::Key::Numpad0, "Numpad 0" },
    BindableKey{ Keyboard::Key::Numpad1, "Numpad 1" },
    BindableKey{ Keyboard::Key::Numpad2, "Numpad 2" },
    BindableKey{ Keyboard::Key::Numpad3, "Numpad 3" },
    BindableKey{ Keyboard::Key::Numpad4, "Numpad 4" },
    BindableKey{ Keyboard::Key::Numpad5, "Numpad 5" },
    BindableKey{ Keyboard::Key::Numpad6, "Numpad 6" },
    BindableKey{ Keyboard::Key::Numpad7, "Numpad 7" },
    BindableKey{ Keyboard::Key::Numpad8, "Numpad 8" },
    BindableKey{ Keyboard::Key::Numpad9, "Numpad 9" },
    BindableKey{ Keyboard::Key::F1, "F1" },
    BindableKey{ Keyboard::Key::F2, "F2" },
    BindableKey{ Keyboard::Key::F3, "F3" },
    BindableKey{ Keyboard::Key::F4, "F4" },
    BindableKey{ Keyboard::Key::F5, "F5" },
    BindableKey{ Keyboard::Key::F6, "F6" },
    BindableKey{ Keyboard::Key::F7, "F7" },
    BindableKey{ Keyboard::Key::F8, "F8" },
    BindableKey{ Keyboard::Key::F9, "F9" },
    BindableKey{ Keyboard::Key::F10, "F10" },
    BindableKey{ Keyboard::Key::F11, "F11" },
    BindableKey{ Keyboard::Key::F12, "F12" },
    BindableKey{ Keyboard::Key::F13, "F13" },
    BindableKey{ Keyboard::Key::F14, "F14" },
    BindableKey{ Keyboard::Key::F15, "F15" },
    BindableKey{ Keyboard::Key::Pause, "Pause" },
    BindableKey{ Keyboard::Key::BrowserBack, "Back" },
    BindableKey{ Keyboard::Key::BrowserForward, "Forward" },
    BindableKey{ Keyboard::Key::BrowserRefresh, "Refresh" },
    BindableKey{ Keyboard::Key::BrowserStop, "Stop" },
    BindableKey{ Keyboard::Key::BrowserSearch, "Search" },
    BindableKey{ Keyboard::Key::BrowserFavorites, "Favorites" },
    BindableKey{ Keyboard::Key::BrowserHome, "Home" },
    BindableKey{ Keyboard::Key::Capital, "Caps Lock" },

    // Mouse
    // BindableKey{ Mouse::Button::Left, "Left Mouse Button" }, # DISABLED
    BindableKey{ Mouse::Button::Right, "Right Mouse Button" },
    BindableKey{ Mouse::Button::Middle, "Middle Mouse Button" },
    BindableKey{ Mouse::Button::Button4, "Mouse Button 4" },
    BindableKey{ Mouse::Button::Button5, "Mouse Button 5" },
    BindableKey{ Mouse::Button::Button6, "Mouse Button 6" },
    BindableKey{ Mouse::Button::Button7, "Mouse Button 7" },
    BindableKey{ Mouse::Button::Button8, "Mouse Button 8" },

    // Joystick
    BindableKey{ Joystick::Button::Button1, "Joy Button 1" },
    BindableKey{ Joystick::Button::Button2, "Joy Button 2" },
    BindableKey{ Joystick::Button::Button3, "Joy Button 3" },
    BindableKey{ Joystick::Button::Button4, "Joy Button 4" },
    BindableKey{ Joystick::Button::Button5, "Joy Button 5" },
    BindableKey{ Joystick::Button::Button6, "Joy Button 6" },
    BindableKey{ Joystick::Button::Button7, "Joy Button 7" },
    BindableKey{ Joystick::Button::Button8, "Joy Button 8" },
    BindableKey{ Joystick::Button::Button9, "Joy Button 9" },
    BindableKey{ Joystick::Button::Button10, "Joy Button 10" },
    BindableKey{ Joystick::Button::Button11, "Joy Button 11" },
    BindableKey{ Joystick::Button::Button12, "Joy Button 12" },
    BindableKey{ Joystick::Button::Button13, "Joy Button 13" },
    BindableKey{ Joystick::Button::Button14, "Joy Button 14" },
    BindableKey{ Joystick::Button::Button15, "Joy Button 15" },
    BindableKey{ Joystick::Button::Button16, "Joy Button 16" },
    BindableKey{ Joystick::Button::Button17, "Joy Button 17" },
    BindableKey{ Joystick::Button::Button18, "Joy Button 18" },
    BindableKey{ Joystick::Button::Button19, "Joy Button 19" },
    BindableKey{ Joystick::Button::Button20, "Joy Button 20" },
    BindableKey{ Joystick::Button::Button21, "Joy Button 21" },
    BindableKey{ Joystick::Button::Button22, "Joy Button 22" },
    BindableKey{ Joystick::Button::Button23, "Joy Button 23" },
    BindableKey{ Joystick::Button::Button24, "Joy Button 24" },
    BindableKey{ Joystick::Button::Button25, "Joy Button 25" },
    BindableKey{ Joystick::Button::Button26, "Joy Button 26" },
    BindableKey{ Joystick::Button::Button27, "Joy Button 27" },
    BindableKey{ Joystick::Button::Button28, "Joy Button 28" },
    BindableKey{ Joystick::Button::Button29, "Joy Button 29" },
    BindableKey{ Joystick::Button::Button30, "Joy Button 30" },
    BindableKey{ Joystick::Button::Button31, "Joy Button 31" },
    BindableKey{ Joystick::Button::Button32, "Joy Button 32" },
    BindableKey{ Joystick::Button::DpadLeft, "Joy D-pad Left" },
    BindableKey{ Joystick::Button::DpadRight, "Joy D-pad Right" },
    BindableKey{ Joystick::Button::DpadUp, "Joy D-pad Up" },
    BindableKey{ Joystick::Button::DpadDown, "Joy D-pad Down" },
};

const BindableKey* GetBindableKey(BindableKey::Key_t key)
{
    auto it = std::find_if(
        BindableKeys.begin(), BindableKeys.end(),
        [&key](const BindableKey& bindableKey) { return key == bindableKey.key; });

    if (it != BindableKeys.end())
    {
        return &*it;
    }

    return nullptr;
}

HRY_NS_END
