name: Build release files

on: workflow_dispatch

jobs:
  build-debug:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config Debug --target hry-core

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: hry-core-debug
          path: |
            ${{github.workspace}}/build/hry-core.dll
            ${{github.workspace}}/build/hry-core.lib

  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --target hry-core

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: hry-core-release
          path: |
            ${{github.workspace}}/build/hry-core.dll
            ${{github.workspace}}/build/hry-core.lib
